###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

services:

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - '/run/desktop/mnt/host/d/Test1php/Test1Php/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '55000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - '/run/desktop/mnt/host/d/Test1php/Test1Php/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            XDEBUG_MODE: 'debug'
            XDEBUG_CONFIG: 'client_host=host.docker.internal'

    webserver_8080:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - '/run/desktop/mnt/host/d/Test1php/Test1Php/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'
